service: tfgm-platform-display-serverless

provider:
  name: aws
  profile: taylorjg
  runtime: nodejs24.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    TFGM_API_URL: https://apiary.tfgm.com
  httpApi:
    cors: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true

functions:
  searchLocations:
    handler: src/handlers/search-locations.handler
    timeout: 10
    events:
      - httpApi:
          path: /search-locations
          method: get

  getTrams:
    handler: src/handlers/get-trams.handler
    timeout: 10
    events:
      - httpApi:
          path: /trams
          method: get
